apiVersion: v1
kind: Service

metadata:
  name: llm-security-gateway-service

spec:
  selector:
    app: llm-security-gateway

  ports:
  - protocol: TCP
    port: 80
    targetPort: 8000

  type: LoadBalancer